(function() {var implementors = {};
implementors['typenum'] = ["impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.BitXor.html' title='core::ops::BitXor'>BitXor</a>&lt;<a class='struct' href='typenum/bit/struct.B0.html' title='typenum::bit::B0'>B0</a>&gt; for <a class='struct' href='typenum/bit/struct.B0.html' title='typenum::bit::B0'>B0</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.BitXor.html' title='core::ops::BitXor'>BitXor</a>&lt;<a class='struct' href='typenum/bit/struct.B0.html' title='typenum::bit::B0'>B0</a>&gt; for <a class='struct' href='typenum/bit/struct.B1.html' title='typenum::bit::B1'>B1</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.BitXor.html' title='core::ops::BitXor'>BitXor</a>&lt;<a class='struct' href='typenum/bit/struct.B1.html' title='typenum::bit::B1'>B1</a>&gt; for <a class='struct' href='typenum/bit/struct.B0.html' title='typenum::bit::B0'>B0</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.BitXor.html' title='core::ops::BitXor'>BitXor</a>&lt;<a class='struct' href='typenum/bit/struct.B1.html' title='typenum::bit::B1'>B1</a>&gt; for <a class='struct' href='typenum/bit/struct.B1.html' title='typenum::bit::B1'>B1</a>","impl&lt;Ur: <a class='trait' href='typenum/uint/trait.Unsigned.html' title='typenum::uint::Unsigned'>Unsigned</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.BitXor.html' title='core::ops::BitXor'>BitXor</a>&lt;Ur&gt; for <a class='struct' href='typenum/uint/struct.UTerm.html' title='typenum::uint::UTerm'>UTerm</a>","impl&lt;Ul: <a class='trait' href='typenum/uint/trait.Unsigned.html' title='typenum::uint::Unsigned'>Unsigned</a>, Bl: <a class='trait' href='typenum/bit/trait.Bit.html' title='typenum::bit::Bit'>Bit</a>, Ur: <a class='trait' href='typenum/uint/trait.Unsigned.html' title='typenum::uint::Unsigned'>Unsigned</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.BitXor.html' title='core::ops::BitXor'>BitXor</a>&lt;Ur&gt; for <a class='struct' href='typenum/uint/struct.UInt.html' title='typenum::uint::UInt'>UInt</a>&lt;Ul, Bl&gt; <span class='where'>where <a class='struct' href='typenum/uint/struct.UInt.html' title='typenum::uint::UInt'>UInt</a>&lt;Ul, Bl&gt;: <a class='trait' href='typenum/__private/trait.PrivateXor.html' title='typenum::__private::PrivateXor'>PrivateXor</a>&lt;Ur&gt;, <a class='struct' href='typenum/uint/struct.UInt.html' title='typenum::uint::UInt'>UInt</a>&lt;Ul, Bl&gt;::Output: <a class='trait' href='typenum/__private/trait.Trim.html' title='typenum::__private::Trim'>Trim</a></span>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
